name: Fix (Dry run)
on:
  pull_request:
    branches: master

jobs:
  fix-dryrun:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run fix
        run: go run ./cmd/main.go --config=./.github/assets.config.yaml --script=fixer

      - name: Show fix result (diff)
        run: |
          git config core.ignorecase false
          git status
          git diff

      - name: Run check
        run: go run ./cmd/main.go --config=./.github/assets.config.yaml --script=checker