name: Pull Request CI
on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  pull_request_ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: bahmutov/npm-install@v1
    - name: Run check (sanity only)
      run: npm run check-sanity
    - name: Run test
      run: npm t
    - name: Run lint
      run: npm run lint