name: Upload to IPFS
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  upload-ipfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: aquiladev/ipfs-action@v0.1.5
      #   id: upload
      #   with:
      #     path: ./blockchains
      #     service: pinata
      #     pinataKey: ${{ secrets.PINATA_KEY }}
      #     pinataSecret: ${{ secrets.PINATA_SECRET }}
      #     pinataPinName: blockchains
      #     timeout: 180000
      #     verbose: false
      - uses: aquiladev/ipfs-action@v0.1.5
        id: upload-dapps
        with:
          path: ./dapps
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
          pinataPinName: dapps
          verbose: false
